trigger: none
    
pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: DockerInstaller@0
  displayName: Docker install
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  displayName: Docker build
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'boykoant/sample-node'
    command: 'build'
    Dockerfile: '00-builds-automation/samples/frontend/docker/Dockerfile'
    buildContext: '00-builds-automation/samples/frontend/'
    tags: |
      $(Build.BuildNumber)
      latest

- task: Docker@2
  displayName: Docker push
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'boykoant/sample-node'
    command: 'push'
    tags: |
      $(Build.BuildNumber)
      latest